version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings  # Указываем правильный путь к settings.py
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application  # Указываем правильный путь к wsgi.py
