services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password

  web:
    build: .
    command: >
      sh -c "while !</dev/tcp/db/5432; do sleep 1; done;
      python manage.py migrate && gunicorn --bind 0.0.0.0:8000 test.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:  # Убедись, что эта строка есть
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=test.settings
