version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
